name: Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    - name: Merge to main
      if: github.ref == 'refs/heads/dev' && success()
      run: |
        git config --global user.email "your.email@example.com"
        git config --global user.name "Your Name"
        git fetch origin dev
        git merge --allow-unrelated-histories -X theirs -m "Merge dev into main" origin/dev
        git push https://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@github.com/codestiven/Practica-Pruebas-unitarias-con-github-actions.git main
