name: Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    - name: Merge to main
      if: github.ref == 'refs/heads/dev' && success()
      run: |
        git merge --allow-unrelated-histories dev
        git push
