    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    - name: Merge to main
      if: github.ref == 'refs/heads/dev' && success()
      run: git merge --ff-only refs/heads/dev
